# Playbook para instalar as minhas coisas no meu ubuntu
# TODO GRUNT, Android Studio, PIP

---
- hosts: localhost
  remote_user: felipedemorais
  sudo: yes
  tasks:
   - name: Install virtualenvwrapper
     pip: name=virtualenvwrapper state=present

   - name: python-apt(dependency of the apt_repository)
     apt: name=python-apt update_cache=yes state=present

   - name: Spotify repo key
     apt_key: keyserver=keyserver.ubuntu.com id=94558F59 state=present

   - name: RVM key
     apt_key: keyserver=hkp://keys.gnupg.net id=409B6B1796C275462A1703113804BB82D39DC0E3

   - name: hipchat key
     apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present

   - name: add repositories of sublime, gimp, RVM
     apt_repository: repo={{ item }} update_cache=yes state=present
     with_items:
     # Sublime 3 repo
     - ppa:webupd8team/sublime-text-3
     # Gimp repo
     - ppa:otto-kesselgulasch/gimp
     # RVM repo
     - ppa:rael-gc/rvm
     # Pop Corn Time repo
     - ppa:webupd8team/popcorntime

   - name: Google Chrome, HipChat and Spotify repo
     apt_repository: repo="{{ item }}" update_cache=yes state=present
     with_items:
     # Google Chrome repo
     - deb http://dl.google.com/linux/chrome/deb stable main
     # # HipChat repo
     - deb http://downloads.hipchat.com/linux/apt stable main
     # # Spotify repo
     - deb http://repository.spotify.com stable non-free

   - name: Installing Packages
     apt: name={{ item }} update_cache=yes state=present
     with_items:
     # Install sublime-text-3
     - sublime-text-installer
     # Install jre 7
     - openjdk-7-jre
     # Install jdk 7
     - openjdk-7-jdk
     # Install terminator
     -  terminator
     # Installing Google-Chrome
     - google-chrome-stable
     # Install Gimp
     - gimp
     # Install Git
     - git
     # Install Skype
     - skype
     # Install Node JS
     - nodejs
     # Install npm
     - npm
     # Install HipChat
     - hipchat
     # Install Spotify
     - spotify-client
     # Install Ruby + RVM
     - ruby-full
     # Install curl
     - curl
     # Install RVM
     - rvm
     # Install Pop Corn Time
     - popcorn-time
     # Install Python pip
     - python-pip
     # Install header files for libpq5 (PostgreSQL library)
     - libpq-dev
     # Install gcc
     - gcc
     # Install libmysqlclient-dev
     - libmysqlclient-dev

   - name: Link to s from subl
     file: src=/usr/bin/subl dest=/usr/bin/s state=link

   - name: link from nodejs to node
     file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
